openapi: 3.0.2

info:
  title: Orders Core API
  version: 1.0.0
  description: Enable orders platform
  contact:
    name: Gabriel M. Miranda
    email: gabrielmirandatt@gmail.com
    url: https://gabrielmirandatt.com
  license:
    name: Apache 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0'

tags:
  - name: orders
    description: Handling orders

servers:
  - url: http://localhost:8080

paths:
  /orders:
    get:
      tags:
        - orders
      summary: Find Orders By Query
      description: Filter orders by parameters
      operationId: findOrdersByQuery
      parameters:
        - name: status
          in: query
          description: Status values that need to be considered for filter
          required: false
          explode: true
          schema:
            $ref: '#/components/schemas/OrderStatusDTO'
      responses:
        '200':
          description: Order search response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OrderResponse'
                example:
                  SUCCESS_SEARCH_ORDER_RESPONSE:
                    value:
                      - id: "12345678-ORDR-1009-20-08"
                        ticketId: "12345678"
                        status: "created"
                        price: 20.50
                        customer:
                          cpf: "038.573.411-57"
                        shippingAddress:
                          street: "Vila Olivo"
                          city: "Valinhos"
                          state: "SP"
                          zip: "13011-300"
                        notification: "(19) 99644-3590"
                        items:
                          - itemId: "12345678-ORDI-1009-20-08"
                            product:
                              id: "12345678-PRDC-1009-20-08"
                              name: "X-Burger"
                              price: 10.90
                            extras:
                              - ingredient:
                                  id: "12345678-INGR-1009-20-08"
                                  name: "Costela meat"
                                  price: 2.90
                                quantity: 1

        '401':
          description: Not Authorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                UNAUTHORIZED_RESPONSE:
                  value:
                    status: 401
                    message: Unauthorized
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                FORBIDDEN_RESPONSE:
                  value:
                    status: 403
                    message: Forbidden
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                BAD_REQUEST_RESPONSE:
                  value:
                    status: 400
                    message: Bad Request
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                INTERNAL_ERROR_RESPONSE:
                  value:
                    status: 500
                    message: Internal Server Error
    post:
      tags:
        - orders
      summary: Add New Order
      description: Add a new order in the restaurant
      operationId: addOrder
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrderRequest'
            example:
              ORDER_REQUEST:
                value:
                  customer:
                    cpf: "038.573.411-57"
                  shippingAddress:
                    street: "Vila Olivo"
                    city: "Valinhos"
                    state: "SP"
                    zip: "13011-300"
                  notification: "(19) 99644-3590"
                  items:
                    - productId: "12345678-PRDC-2018-10-10"
                      extras:
                        - ingredientId: "12345678-INGR-2018-10-10"
                          quantity: 2
                      quantity: 2
      responses:
        '201':
          description: Order created response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderCreated'
              example:
                SUCCESS_CREATED_ORDER_RESPONSE:
                  value:
                    ticketId: "12345678"
        '401':
          description: Not Authorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                UNAUTHORIZED_RESPONSE:
                  value:
                    status: 401
                    message: Unauthorized
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                FORBIDDEN_RESPONSE:
                  value:
                    status: 403
                    message: Forbidden
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                BAD_REQUEST_RESPONSE:
                  value:
                    status: 400
                    message: Bad Request
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                INTERNAL_ERROR_RESPONSE:
                  value:
                    status: 500
                    message: Internal Server Error
  /orders/{orderId}:
    get:
      tags:
        - orders
      summary: Find Order By ID
      description: Returns a single order by ID
      operationId: getOrderById
      parameters:
        - name: orderId
          in: path
          description: ID of order to return
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Order search response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderResponse'
              example:
                SUCCESS_CREATED_ORDER_RESPONSE:
                  value:
                    id: "12345678-ORDR-1009-20-08"
                    ticketId: "12345678"
                    status: "created"
                    price: 20.50
                    customer:
                      cpf: "038.573.411-57"
                    shippingAddress:
                      street: "Vila Olivo"
                      city: "Valinhos"
                      state: "SP"
                      zip: "13011-300"
                    notification: "(19) 99644-3590"
                    items:
                      - itemId: "12345678-ORDI-1009-20-08"
                        product:
                          id: "12345678-PRDC-1009-20-08"
                          name: "X-Burger"
                          price: 10.90
                        extras:
                          - ingredient:
                              id: "12345678-INGR-1009-20-08"
                              name: "Costela meat"
                              price: 2.90
                            quantity: 1
        '401':
          description: Not Authorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                UNAUTHORIZED_RESPONSE:
                  value:
                    status: 401
                    message: Unauthorized
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                FORBIDDEN_RESPONSE:
                  value:
                    status: 403
                    message: Forbidden
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                BAD_REQUEST_RESPONSE:
                  value:
                    status: 400
                    message: Bad Request
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                NOT_FOUND_RESPONSE:
                  value:
                    status: 404
                    message: Not Found
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                INTERNAL_ERROR_RESPONSE:
                  value:
                    status: 500
                    message: Internal Server Error
  /orders/{orderId}/status/{status}:
    post:
      tags:
        - orders
      summary: Change Order Status
      description: Changes order status given step
      operationId: changeOrderStatus
      parameters:
        - name: orderId
          in: path
          description: ID of order to change
          required: true
          schema:
            type: string
        - name: status
          in: path
          description: Status to change
          required: true
          explode: true
          schema:
            $ref: '#/components/schemas/OrderStatusDTO'
      responses:
        '204':
          description: Ok
        '401':
          description: Not Authorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                UNAUTHORIZED_RESPONSE:
                  value:
                    status: 401
                    message: Unauthorized
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                FORBIDDEN_RESPONSE:
                  value:
                    status: 403
                    message: Forbidden
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                BAD_REQUEST_RESPONSE:
                  value:
                    status: 400
                    message: Bad Request
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                UNPROCESSABLE_ENTITY_RESPONSE:
                  value:
                    status: 422
                    message: Unprocessable Entity
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                INTERNAL_ERROR_RESPONSE:
                  value:
                    status: 500
                    message: Internal Server Error

components:
  schemas:
    AddressDTO:
      type: object
      description: Address in case of delivery
      properties:
        street:
          type: string
          maximum: 30
        city:
          type: string
          maximum: 30
        state:
          type: string
          minimum: 2
          maximum: 2
        zip:
          type: string
          pattern: '^[0-9]{5}-[0-9]{3}$'
    OrderStatusDTO:
      type: string
      description: Status of the order
      enum:
        - created
        - preparation
        - packaging
        - pickup
        - delivery
        - completed
    CustomerDTO:
      type: object
      description: Identified Customer in Order
      required:
        - cpf
      properties:
        cpf:
          type: string
          description: Customer identified CPF
          pattern: '^\d{3}\.\d{3}\.\d{3}-\d{2}$'
    OrderExtraRequest:
      type: object
      required:
        - ingredientId
        - quantity
      properties:
        ingredientId:
          type: string
          description: IngredientId of the extra
        quantity:
          type: integer
          minimum: 1
          maximum: 2
          description: Quantity of extras of same ingredient
    OrderItemRequest:
      type: object
      required:
        - productId
        - quantity
      properties:
        productId:
          type: string
          description: ProductId of the item
        extras:
          type: array
          minimum: 1
          maximum: 3
          description: Extras ingredients of the product
          items:
            $ref: '#/components/schemas/OrderExtraRequest'
        quantity:
          type: integer
          minimum: 1
          maximum: 10
          description: Quantity of same product with same extras
    OrderRequest:
      type: object
      required:
        - items
      properties:
        customer:
          $ref: '#/components/schemas/CustomerDTO'
        shippingAddress:
          $ref: '#/components/schemas/AddressDTO'
        notification:
          type: string
          description: Cellphone for additional notification when ready
        items:
          type: array
          description: Items of the Order
          items:
            $ref: '#/components/schemas/OrderItemRequest'
    OrderCreated:
      type: object
      required:
        - ticketId
      properties:
        ticketId:
          type: string
          description: Generated ticketId for the Order
          minimum: 8
          maximum: 8
    IngredientResponse:
      type: object
      description: Extra ingredient of the product
      required:
        - id
        - name
        - price
      properties:
        id:
          type: string
          description: ID of the Ingredient
          pattern: '^\d{8}-INGR-\d{4}-\d{2}-\d{2}$'
        name:
          type: string
          description: Name of the Ingredient
          maximum: 30
        price:
          type: number
          format: double
          description: Price of the ingredient
          minimum: 0.1
          maximum: 10000.0
    ProductResponse:
      type: object
      description: Product of the item
      required:
        - id
        - name
        - price
      properties:
        id:
          type: string
          description: ID of the Product
          pattern: '^\d{8}-PRDC-\d{4}-\d{2}-\d{2}$'
        name:
          type: string
          description: Name of the Product
          maximum: 30
        price:
          type: number
          format: double
          description: Price of the product
          minimum: 0.1
          maximum: 10000.0
    OrderExtraResponse:
      type: object
      required:
        - ingredient
        - quantity
      properties:
        ingredient:
          $ref: '#/components/schemas/IngredientResponse'
        quantity:
          type: number
          description: Extra ingredient of the product
          minimum: 1
          maximum: 2
    OrderItemResponse:
      type: object
      required:
        - itemId
        - product
      properties:
        itemId:
          type: string
          description: ID of the item
          pattern: '^\d{8}-ORDI-\d{4}-\d{2}-\d{2}$'
        product:
          $ref: '#/components/schemas/ProductResponse'
        extras:
          type: array
          description: Extras of the Product
          items:
            $ref: '#/components/schemas/OrderExtraResponse'
          minimum: 1
          maximum: 3
    OrderResponse:
      type: object
      required:
        - id
        - ticketId
        - status
        - price
        - items
      properties:
        id:
          type: string
          description: ID of the Order
          pattern: '^\d{8}-ORDR-\d{4}-\d{2}-\d{2}$'
        ticketId:
          type: string
          description: ticketId of the item, sent to customer
          minimum: 8
          maximum: 8
        status:
          $ref: '#/components/schemas/OrderStatusDTO'
        price:
          type: number
          description: Price of the order
          format: double
          minimum: 0.1
          maximum: 10000.0
        customer:
          $ref: '#/components/schemas/CustomerDTO'
        shippingAddress:
          $ref: '#/components/schemas/AddressDTO'
        notification:
          type: string
          description: Mobile phone for additional notification
          pattern: '^\(\d{2}\) \d{4,5}-\d{4}$'
        items:
          type: array
          description: Items of the Order
          items:
            $ref: '#/components/schemas/OrderItemResponse'
          minimum: 1
          maximum: 10
    ErrorResponse:
      type: object
      required:
        - status
        - message
      properties:
        status:
          type: integer
          format: int32
          description: Status of the error
          maximum: 600
        message:
          type: string
          description: Message of the error
          maximum: 100
        code:
          type: string
          description: Specific code of the error
          maximum: 10

#  securitySchemes:
#    hydra:
#      type: openIdConnect
#      openIdConnectUrl: 'https://competent-cori-vgu1750x6j.projects.oryapis.com/.well-known/openid-configuration'
#
#security:
#  - hydra:
#      - orders.write
#      - orders.read